Update pre-push hook.

diff --git a/.git-hooks/hooks/pre-push b/.git-hooks/hooks/pre-push
--- a/.git-hooks/hooks/pre-push
+++ b/.git-hooks/hooks/pre-push
@@ -6,11 +6,29 @@
 
 ### Linting
 printf "\n%s\n" "Pre-push hook activated."
-start_lint=$(date +%s)
 printf "%s\n" "Linting..."
 yapf -ir . --exclude '*ipynb*' --exclude .venv
 isort . --atomic --skip-glob "*ipynb*" --line-width 99
-end_lint=$(date +%s)
-printf "%s\n" "Linting completed for "$(($end_lint-$start_lint))" seconds."
-coverage run -m pytest -x
-coverage report -m
+printf "%s\n" "Linting completed."
+
+### Testing
+printf "\n%s\n" "Executing tests..."
+start_tests=$(date +%s)
+coverage run -m  pytest --durations=0
+test_status=$?
+end_tests=$(date +%s)
+printf "\n%s\n\n\n" "Testing completed for "$(($end_tests-$start_tests))" seconds."
+
+### Coverage
+coverage report | tee /dev/tty | grep TOTAL | awk '{if (int(substr($4, 1, length($4)-1)) < int(100)){print "\nCode coverage test failed. Expected 100%, got "$4"\n"; exit 1} else {print "\nCode coverage test successful.\n"; exit 0}}'
+coverage_status=$?
+
+### MyPy
+printf "\n%s\n" "Mypy results below:"
+mypy . --exclude .venv --install-types --non-interactive # optionally, add: --ignore-missing-imports
+mypy_status=$?
+
+### Exiting
+if [ "$test_status" -ge "$coverage_status" ]; then hook_status="$test_status"; else hook_status="$coverage_status"; fi
+if [ "$test_status" -ne 0 ]; then printf "%s\n" "There are failed tests."; fi
+exit $hook_status
